/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002117",
        "tertiary": "#ffb4aa",
        "on-tertiary-container": "#560d09",
        "tertiary-fixed": "#ffdad5",
        "status-info": "#3B82F6",
        "primary": "#61dbb4",
        "surface-container-lowest": "#090f0d",
        "secondary": "#c6c5d9",
        "on-secondary-fixed-variant": "#454556",
        "surface-container-highest": "#303633",
        "on-primary-fixed-variant": "#00513d",
        "difficulty-easy": "#22C55E",
        "status-error": "#EF4444",
        "surface-bright": "#343b37",
        "surface-container-low": "#171d1a",
        "inverse-primary": "#006c52",
        "primary-fixed-dim": "#61dbb4",
        "on-surface": "#dee4df",
        "on-primary": "#00382a",
        "secondary-fixed-dim": "#c6c5d9",
        "on-surface-variant": "#bccac2",
        "error": "#ffb4ab",
        "surface-variant": "#303633",
        "inverse-on-surface": "#2b322f",
        "difficulty-medium": "#F59E0B",
        "border-light": "#E5E5E7",
        "surface-container-high": "#252b28",
        "on-error": "#690005",
        "primary-container": "#12a480",
        "surface-tint": "#61dbb4",
        "on-secondary": "#2e2f3f",
        "surface-dark": "#171717",
        "outline": "#86948d",
        "surface-dim": "#0f1512",
        "on-background": "#dee4df",
        "border-dark": "#2D2D2D",
        "surface": "#0f1512",
        "surface-light": "#FFFFFF",
        "status-success": "#10A37F",
        "on-secondary-container": "#b4b3c7",
        "on-error-container": "#ffdad6",
        "secondary-container": "#454556",
        "on-primary-container": "#003024",
        "surface-container": "#1b211e",
        "on-tertiary": "#5f140f",
        "on-secondary-fixed": "#191a29",
        "on-tertiary-fixed": "#410001",
        "on-tertiary-fixed-variant": "#7e2b22",
        "outline-variant": "#3d4a44",
        "tertiary-fixed-dim": "#ffb4aa",
        "background": "#0f1512",
        "tertiary-container": "#dc7265",
        "bg-dark": "#0D0D0D",
        "secondary-fixed": "#e2e0f5",
        "bg-light": "#F7F7F8",
        "error-container": "#93000a",
        "surface-muted-dark": "#212121",
        "inverse-surface": "#dee4df",
        "difficulty-hard": "#EF4444",
        "status-warning": "#F59E0B",
        "primary-fixed": "#7ff8cf",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "0.5rem",
        gutter: "1.5rem",
        "stack-md": "1rem",
        "margin-page": "2rem",
        "stack-lg": "2rem",
        "container-max": "1280px",
      },
      fontFamily: {
        "code-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        h3: ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        h1: ["Manrope", "sans-serif"],
        h2: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "code-md": ["14px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        h1: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
