server.port=8080
spring.application.name=api-gateway

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# JWT Configuration (same as auth-service)
jwt.secret=W9XVo1vRqa5a6o2U4I2h0N2kTP5RYQqxwM9F92kglZptFGTQELXYUu5S0uEVwL20sU0DdjlZql33H0V6jpmKr5d9pmG6coy0
jwt.issuer=http://api.codechallenge.com

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.codechallenge.gateway=DEBUG

